# Generated by Django 5.0 on 2023-12-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=20)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('Technical', 'Techincal'), ('Non-techinal', 'Non-techincal')], max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
