# Generated by Django 5.0 on 2023-12-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=10)),
                ('about', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='college',
            name='type',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Non-technical', 'Non-techincal'), ('Both', 'Both')], max_length=50),
        ),
    ]
